fix: escape cells of CSV download
Dataport/terminfinder-frontend pull request #196
Opened 2024-04-24 18:35 UTC by jase88

- escaping every CSV cell (untouched if not necessary)
- ensuring proper file name of CSV to download
  - for example too long file names that exceed 255 chars ([Long file names](https://en.wikipedia.org/wiki/Long_filename#:~:text=The%20maximum%20length%20of%20a,root%20folder%20of%20any%20drive.)) 
- made sure texts are localized 
- add unit test framework `jest` with Angulars experimental builder `@angular-devkit/build-angular:jest`
  - alternatively we could also 
    - a) use `jest-preset-angular` (which would add another package and some more configuration files) 
    - b) use `vitest` via `@analogjs/vite-plugin-angular` (which would add a layer of `analogjs` for testing)
  - happy to discuss this

fixes #69

2024-04-30 10:06 UTC, jase88 commented
@tjorbo ready for review or happy to discuss.
If necessary, I can also outsource things to separate PRs.

Bumping `rxjs` for example is also done here: https://github.com/Dataport/terminfinder-frontend/pull/200

2024-05-06 14:40 UTC, tjorbo requested changes
Hi @jase88,
Thank you for your PR.

I have reviewed your changes and agree with most of them.

Most of my requested changes are related to translations. Nice idea to translate the csv file as well. But is it possible to move the translation properties so we don't have to add a csvExport property?

Also, I found a serious bug while testing your changes. https://github.com/Dataport/terminfinder-frontend/issues/203 It is probably not a bug in your code, but if you could do a rebase, it would be clearer which changes are yours. We want to prevent merge commits by rebasing in general. So I will wait with rebasing dependabot's PRs until your PR is done. (To avoid conflicts in package.json)

Thanks again for your contribution.

2024-05-06 14:40 UTC, tjorbo commented on src/app/poll/csv-utils.spec.ts
> +    ["line1\rline2", '"line1\rline2"'],
```suggestion
    ["line1\nline2", '"line1 line2"'],
    ["line1\rline2", '"line1 line2"'],
```

In my opinion we should not have these control characters as they could break the csv format. If the user enters \\ as a name, the validator will mark the field as invalid.

2024-05-06 14:40 UTC, tjorbo commented on docker-replace-parameters.sh
> +CUSTOMER_ID=$(echo "$CUSTOMER_ID" || echo "00000000-0000-0000-0000-000000000000")
These changes are already in the main branch. It would be very helpful if you could do a rebase. We try to avoid merge commits. Thank you 👍

2024-05-06 14:40 UTC, tjorbo commented on src/app/poll/poll-form-helper.service.ts
> +      parts.push(this.translate.instant("poll.csvExport.timeAt", { time }));
```suggestion
      parts.push(this.translate.instant("time.timeAt", { time }));
```

2024-05-06 14:40 UTC, tjorbo commented on src/locales/de-DE-du.json
> +      "timeAt": "um {{time}}",
Please move into "time.timeAt"

2024-05-06 14:40 UTC, tjorbo commented on src/app/poll/poll-form-helper.service.ts
> +        this.translate.instant("poll.csvExport.dateTo", { date }).trim(),
```suggestion
        this.translate.instant("date.dateTo", { date }).trim(),
```

2024-05-06 14:40 UTC, tjorbo commented on src/locales/de-DE-du.json
> +      "dateTo": "bis {{date}}"
Please move to "date.dateTo"

2024-05-06 14:40 UTC, tjorbo commented on src/app/poll/poll-form-helper.service.ts
> +      parts.push(this.translate.instant("poll.csvExport.timeAt", { time }));
```suggestion
      parts.push(this.translate.instant("time.timeAt", { time }));
```

2024-05-06 14:40 UTC, tjorbo commented on src/app/poll/poll-form-helper.service.ts
> +        return this.translate.instant("poll.csvExport.statusAccepted");
```suggestion
        return this.translate.instant("votingStatus.accepted");
```

I'm going to move the "date.accepted" to "votingStatus.accepted", too.

2024-05-06 14:40 UTC, tjorbo commented on src/app/poll/poll-form-helper.service.ts
> +        return this.translate.instant("poll.csvExport.statusQuestionable");
```suggestion
        return this.translate.instant("votingStatus.questionable");
```

2024-05-06 14:40 UTC, tjorbo commented on src/app/poll/poll-form-helper.service.ts
> +        return this.translate.instant("poll.csvExport.statusDeclined");
```suggestion
        return this.translate.instant("votingStatus.declined");
```

2024-05-06 14:40 UTC, tjorbo commented on src/app/poll/poll-form-helper.service.ts
> +        return this.translate.instant("poll.csvExport.statusUnknown");
```suggestion
        return this.translate.instant("votingStatus.unknown");
```

2024-05-06 14:40 UTC, tjorbo commented on src/locales/de-DE-du.json
> +      "statusUnknown": "unbekannt",
Please move into "votingStatus.
- accepted"
- questionable"
- declined"
- unknown

Thanks :)

2024-05-06 14:40 UTC, tjorbo commented on src/app/poll/poll-form-helper.service.ts
> +        this.translate.instant("poll.csvExport.participants"),
```suggestion
        this.translate.instant("participant.participants"),
```

2024-05-06 14:40 UTC, tjorbo commented on src/app/poll/poll-form-helper.service.ts
> +      this.translate.instant("poll.csvExport.fileTitlePrefix"),
```suggestion
      this.translate.instant("poll.poll"),
```

2024-05-06 14:40 UTC, tjorbo commented on src/locales/de-DE-du.json
> +      "participants": "Teilnehmer:innen",
```suggestion
```

Using "poll.poll" and "participants.participants"

2024-05-06 14:40 UTC, tjorbo commented on src/locales/de-DE-sie.json
> +    },
```suggestion
```

Please look at suggestions of de-DE-du.json - Thank you.

2024-05-06 14:40 UTC, tjorbo commented on src/locales/en-EN.json
> +    },
```suggestion
```

Please look at suggestions of de-DE-du.json - Thank you.

2024-05-06 14:40 UTC, tjorbo commented on src/locales/platt.json
> +    },
```suggestion
```

Please look at suggestions of de-DE-du.json - Thank you.

2024-05-06 14:40 UTC, tjorbo commented on package.json
> +    "jest": "29.7.0",
It would be nice if you could rebuild the package-lock.json. Thank you.

2024-05-08 08:07 UTC, jase88 commented on src/app/poll/csv-utils.spec.ts
> +    ["line1\rline2", '"line1\rline2"'],
I agree that this implementation is very generic and mostly theoretical issues that may not occur in the project.

The API also seems to check that the name of a participant does not contain any control characters. The poll title does not seem to be checked in the API, but does not appear in the CSV export either

What do you suggest?  I prefer a general implementation that also covers changes to the features.

2024-05-08 10:42 UTC, tjorbo commented on src/app/poll/csv-utils.spec.ts
> +    ["line1\rline2", '"line1\rline2"'],
You're right, I agree with your suggestion.

2024-05-08 10:54 UTC, hassmal commented on src/locales/platt.json
> +    "timeAt": ".",
@tjorbo where did platt translations generally came from? They are missing here and we obviously can't expect people to translate this. Are we okay with those being empty for the moment?

2024-05-08 10:54 UTC, hassmal commented on src/locales/platt.json
> +    "timeAt": ".",
we can atleast show the time

```suggestion
    "timeAt": "{{time}}",
```

2024-05-08 10:54 UTC, hassmal commented on src/locales/platt.json
> +    "dateTo": ".",
we can atleast show the date

```suggestion
    "dateTo": "{{date}}",
```

2024-05-08 11:01 UTC, tjorbo commented on src/locales/platt.json
> +    "timeAt": ".",
It was an experimental feature that didn't make it to production. It's ok to be empty now.

2024-05-08 11:32 UTC, tjorbo commented on src/app/poll/poll-form-helper.service.spec.ts
> +        "Teilnehmende,01/10/2024 um 1:00 PM bis 01/11/2024 um 7:00 AM,01/20/2024 um 2:00 PM bis um 7:00 PM",
```suggestion
        `Teilnehmende,${moment("2024-01-10T12:00:00.000Z").format('MM/DD/YYYY [um] h:mm A')} bis ${moment("2024-01-11T06:00:00.000Z").format('MM/DD/YYYY [um] h:mm A')},${moment("2024-01-20T13:00:00.000Z").format('MM/DD/YYYY [um] h:mm A')} bis um ${moment("2024-01-21T18:00:00.000Z").format('h:mm A')}`,
```

GitHub Actions servers are on different time zones.

2024-05-08 11:35 UTC, tjorbo approved these changes

2024-05-15 05:26 UTC, closed without merging

2024-05-15 05:34 UTC, jase88 commented
@tjorbo 
Also thank you for your patience and helping out with the mixed branch commits.

force pushing to my fork automatically closed this PR, wasn't aware of that.

So I pushed the branch you mentioned to my fork and created a new PR: https://github.com/Dataport/terminfinder-frontend/pull/209

Hope thats fine.

2024-05-15 11:44 UTC, tjorbo commented
@jase88 I didn't know that either. Just merged #209. Thanks for the first contribution to this project. ❤️